### PR TITLE
Implementing .NET Standards 1.5, .NET Standards 1.6, .NET Standards 2.0 and .NET Framework 4.6

### PR DESCRIPTION
**Pull request by atp-tha**
Our team's new .NET stack is .NET 2.0 Core which implement .NET Standard. So I implement this PR for business needs.

After using it for a while without encountering bugs, I decided that I'd contribute to the community.

What I've done:
-implement netstandard1.5, netstandard1.6, netstandard2.0 and net46 for the lib
-implement net45, net46, netcoreapp1.0 and netcoreapp2.0 for tests
-move from Fizzler (which still implement old HtmlAgilityPack) to HtmlAgilityPack.CssSelector
-move from NUnit 2 to 3

### CODE REVIEW

**Comment by atp-tha** [comment]
AppVeyor build failed with MSB4041 error code because it cannot build new .csproj format.

Some actions on CI would be needed before merging this PR. @lukeschafer

**Comment by lukeschafer** [comment]
Sorry, notifications for this project got lost in the aether! 

I will take a look when I get a chance

**Comment by lukeschafer** [comment]
Hi @beam-codegrind - I have update AppVeyor to use VS2017 image. Can you please update the VS version in .sln as part of this PR and we can see if that fixes it?

**Comment by atp-tha** [comment]
Hello @lukeschafer - I updated the version and it didn't work. Judging from the log, I believe try using `dotnet build` command instead of `msbuild` should fix the problem because it run `dotnet restore` before start building.

**Comment by lukeschafer** [comment]
Yep done, thanks mate.

**Comment by lukeschafer** [comment]
Looks like there's an issue pushing nuget package from the build, I'll have to look at that later

**Comment by atp-tha** [comment]
I noticed that AppVeyor only run tests for `net45` and `net46` but the tests should also run for `netcoreapp1.1` and `netcoreapp2.0` too. Should we fix it here in this PR or should I create another issue for this?

**Comment by lukeschafer** [comment]
Depends on whether it's appveyor or not. I have fixed appveyor so it now pushes packages

**Comment by lukeschafer** [comment]
I've sorted it in appveyor and caused a new version to be pushed. Somehow the versioning changed so I bumped the minor version too. Let me know if you get issues

**Pull request merged**
